**Universidad Galileo**

**Ciencia de Datos en Python**

**Nombre: Rodrigo Chang**

# Diferencia entre los tipos de datos *np.ndarray* y *np.matrix*

In [2]:
import numpy as np

## Conceptualmente:

* Las matrices son estrictamente de 2 dimensiones, mientras que el tipo *np.ndarray* son arreglos **multidimensionales**. 

* Los objetos np.matrix son una subclase de np.ndarray, por lo que *heredan* todos los atributos y métodos del tipo *np.ndarray*.


In [4]:
# Con esto vemos la clase "padre" del tipo np.matrix
np.matrix.__bases__

(numpy.ndarray,)

## Diferencia del operador \*

* La principal ventaja de las matrices es que proveen una notación conveniente para la multiplicación matricial.
    * Cuando multiplicamos dos objetos np.matrix, *a* y *b*, entonces *a*b* representa la multiplicación matricial entre *a* y *b*. 
    * Cuando multiplicamos dos objetos np.ndarray, *a* y *b*, entonces *a*b* representa la multiplicación elemento por elemento (*element-wise*) entre *a* y *b*. 

In [14]:
# Multiplicación matricial entre a y b
a = np.mat('4 3; 2 1')
b = np.mat('1 2; 3 4')
a*b

matrix([[13, 20],
        [ 5,  8]])

In [13]:
# Multiplicación entre dos objetos np.ndarray
a_nd = np.array([[4, 3], [2, 1]])
b_nd = np.array([[1, 2], [3, 4]])
a_nd*b_nd


array([[4, 6],
       [6, 4]])

**Nota:** a partir de Python 3.5, para llevar a cabo la multiplicación matricial entre dos objetos *np.ndarray* se puede utilizar el operador **@**.

In [15]:
a_nd @ b_nd

array([[13, 20],
       [ 5,  8]])

## Métodos específicos para matrices

* Otra diferencia importante es que ambos objetos, np.matrix y np.ndarrays tienen el método **.T** para devolver la transpuesta, pero los objetos de matrices tienen también los métodos **.H** para obtener la conjugada transpuesta, e **.I** para la inversa.

In [19]:
# Obteniendo la transpuesta para la matriz a
a.T

matrix([[4, 2],
        [3, 1]])

In [17]:
# Obteniendo la transpuesta para el ndarray a
a_nd.T

array([[4, 2],
       [3, 1]])

In [20]:
# Obteniendo la conjugada transpuesta para a
a.H

matrix([[4, 2],
        [3, 1]])

In [22]:
# Obteniendo la conjugada transpuesta para la matriz a
a.H

matrix([[4, 2],
        [3, 1]])

In [23]:
# Mientras que el ndarray no tiene este método
a_nd.H

AttributeError: 'numpy.ndarray' object has no attribute 'H'

In [24]:
# Y más importante, obtener la inversa:
a.I

matrix([[-0.5,  1.5],
        [ 1. , -2. ]])

In [25]:
# Matriz identidad
a.I * a

matrix([[1., 0.],
        [0., 1.]])

In [26]:
# Mientras que para el nd_array no existe este método
a_nd.I

AttributeError: 'numpy.ndarray' object has no attribute 'I'

## Diferencia del operador \*\*

* Otra diferencia puede ser el uso del operador **\*\***: 
    * Para matrices, **a\*\*2** devuelve el producto matricial a\*a 
    * Para ndarray, **a\*\*2** devuelve a con cada elemento elevado al cuadrado.

In [30]:
# Obteniendo el producto de a*a
a*a

matrix([[22, 15],
        [10,  7]])

In [31]:
# También lo podemos operar así:
a**2

matrix([[22, 15],
        [10,  7]])

In [33]:
# Mientras que para los ndarray, 
# esta operación eleva element-wise
a_nd ** 2

array([[16,  9],
       [ 4,  1]])

#### Fuente: 
https://stackoverflow.com/questions/4151128/what-are-the-differences-between-numpy-arrays-and-matrices-which-one-should-i-u, consultada el día *18 de marzo de 2019*.
